config/routes.rb
Rails.application.routes.draw do
  devise_for :venue_admins, path: 'admin', controllers: {
    registrations: 'admin/registrations'
  }

  devise_scope :venue_admin do
    delete 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  namespace :admin do
    resources :companies, only: [:new, :create]
    resources :offers, only: [:new, :index, :create]

    resources :venues do
      resources :reservations, only: %i[index new create destroy]
      resources :offers, only: %i[new index create]
    end

    resources :offers, only: %i[create edit show update destroy] do
      resources :variants, only: %i[new edit create destroy show update]
      member do
        post 'select_variant'
        delete 'remove_variant'
      end
      collection do
        get 'selected_variants'
      end
    end

    get 'home/index'
    root 'home#index'
  end

  root "home#index"

  resources :venues, only: [:show, :index] do
    collection do
      post :search
      get :search
      get 'selected_variants'
    end
  end

  resources :cart, only: [:index] do
    collection do
      post :select_variant
      delete 'remove_variant/:variant_id', to: 'cart#remove_variant', as: 'remove_variant'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/variant.rb
# app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :offer
  has_and_belongs_to_many :reservations
  validates :price, presence: true
  validates :period,
            uniqueness: { scope: :offer_id,
                          message: 'already exists for this offer. You can only have one price for a given period.' }
end

app/controllers/admin/variants_controller.rb
class Admin::VariantsController < Admin::AdminController
  before_action :set_offer, only: %i[new create edit update show]
  before_action :set_variant, only: %i[edit update destroy show]
  before_action :authenticate_venue_admin!

  def new
    @variant = @offer.variants.build
  end

  def show; end

  def edit; end

  def create
    @variant = @offer.variants.build(variant_params)
    if @variant.save
      respond_to do |format|
        format.html do
          flash[:notice] = 'Variant was successfully created.'
          redirect_to admin_offer_path(@offer)
        end
        format.turbo_stream
      end
    else
      render :new
    end
  end

  def update
    if @variant.update(variant_params)
      respond_to do |format|
        format.html do
          flash[:notice] = 'Variant was successfully updated.'
          redirect_to admin_offer_path(@offer)
        end
        format.turbo_stream
      end
    else
      render :edit
    end
  end

  def destroy
    if @variant
      @variant.destroy
      respond_to do |format|
        format.html { redirect_to @variant.offer, notice: 'Variant was successfully deleted.' }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, alert: 'Variant not found.' }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('notice-container', partial: 'shared/flash',
                                                                        locals: { flash: { alert: 'Variant not found.' } })
        end
      end
    end
  end

  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

  def set_variant
    @variant = Variant.find(params[:id])
  end

  def variant_params
    params.require(:variant).permit(:price, :period, :offer_id)
  end
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  before_action :set_offer, only: [:new, :create]
  before_action :set_variant, only: [:destroy]
  before_action :authenticate_venue_admin!

  def new
    @variant = @offer.variants.build
  end

  def create
    @variant = @offer.variants.build(variant_params)
    if @variant.save
      respond_to do |format|
        format.html { redirect_to venue_path(@offer.venue), notice: 'Variant was successfully created.' }
        format.turbo_stream
      end
    else
      render :new
    end
  end 

  def destroy
    if @variant
      @variant.destroy
      respond_to do |format|
        format.html { redirect_to @variant.offer, notice: 'Variant was successfully deleted.' }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, alert: 'Variant not found.' }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("notice-container", partial: "shared/flash", locals: { flash: { alert: 'Variant not found.' } }) }
      end
    end
  end
  
  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

  def set_variant
    @variant = Variant.find(params[:id])
  end

  def variant_params
    params.require(:variant).permit(:name, :price, :period)
  end
end

app/helpers/variants_helper.rb
module VariantsHelper
  def period_options
    [
      ['Per Day', 'day'],
      ['Per Month', 'month']
    ]
  end
end

app/views/admin/variants/_form.html.erb
<%= form_with(model: [:admin, @offer, @variant]) do |form| %>
  <% if @variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variant.errors.count, "error") %> prohibited this variant from being saved:</h2>
      <ul>
        <% @variant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.number_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, min: 1 %>
  </div>

   <div class="field">
    <%= form.label :period, "Select Period" %>
    <%= form.select :period, options_for_select(period_options) %>
  </div>

  <div class="actions">
    <%= form.submit "Create Variant" %>
    <% if @variant.persisted? %>
      <%= link_to "Cancel", admin_offer_variant_path(@offer, @variant) %>
    <% else %>
      <%= link_to "Cancel", admin_offer_path(@offer) %>
    <% end %>
  </div>
<% end %>

app/views/admin/variants/_variant.html.erb
<turbo-frame id="<%= dom_id(variant) %>">
  <div class="variant" id="<%= dom_id(variant) %>">
    <p>Name: <%= variant.name %></p>
    <p>Price: <%= number_to_currency(variant.price) %></p>
    <p>Period: <%= variant.period %></p>
    <%= link_to 'Edit Variant', edit_admin_offer_variant_path(@offer, variant), class: 'btn btn-outline-primary' %>
    <%= button_to 'Select Variant', select_variant_admin_offer_path(@offer, variant_id: variant.id), method: :post, class: 'btn btn-outline-primary' %>
    <%= link_to 'Delete Variant', admin_offer_variant_path(@offer, variant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
  </div>
</turbo-frame>

app/views/admin/variants/create.turbo_stream.erb
<% if @existing_variant.present? %>
  <%= turbo_stream.append "variants", partial: "admin/variants/variant", locals: { variant: @existing_variant } %>

  <%= turbo_stream.update "notice-container" do %>
    <div class="notice">Variant was successfully updated.</div>
  <% end %>
<% else %>
<% end %>

app/views/admin/variants/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@variant) %>

<%= turbo_stream.update "notice-container" do %>
  <div class="notice">Variant was successfully deleted.</div>
<% end %>

app/views/admin/variants/edit.html.erb
<h1>Edit Variant for <%= @offer.title %></h1>
<turbo-frame id="<%= dom_id(@variant)%>">
  <%= render "form" %>
</turbo-frame>
<%= link_to 'Back', admin_offer_path(@offer) %>

app/views/admin/variants/new.html.erb
<h1>New Variant for <%= @offer.title %></h1>

<turbo-frame id="new_variant">
  <%= render "form" %>
</turbo-frame>
<%= link_to 'Back', admin_offer_path(@offer) %>

app/views/admin/variants/show.html.erb
<%= render "variant", variant: @variant %>