config/routes.rb
Rails.application.routes.draw do
  devise_for :venue_admins, path: 'admin', controllers: {
    registrations: 'admin/registrations'
  }

  devise_scope :venue_admin do
    delete 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  namespace :admin do
    resources :companies, only: [:new, :create]
    resources :offers, only: [:new, :index, :create]

    resources :venues do
      resources :reservations, only: %i[index new create destroy]
      resources :offers, only: %i[new index create]
    end

    resources :offers, only: %i[create edit show update destroy] do
      resources :variants, only: %i[new edit create destroy show update]
      member do
        post 'select_variant'
        delete 'remove_variant'
      end
      collection do
        get 'selected_variants'
      end
    end

    get 'home/index'
    root 'home#index'
  end

  root "home#index"

  resources :venues, only: [:show, :index] do
    collection do
      post :search
      get :search
      get 'selected_variants'
    end
  end

  resources :cart, only: [:index] do
    collection do
      post :select_variant
      delete 'remove_variant/:variant_id', to: 'cart#remove_variant', as: 'remove_variant'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/offer.rb
# app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :venue
  has_many :variants, dependent: :destroy
  has_many :reservations, dependent: :destroy

  accepts_nested_attributes_for :variants, allow_destroy: true
  validates :title, :description, presence: true

  def total_price(selected_variant_ids)
    variants.where(id: selected_variant_ids).sum(:price)
  end
end

app/controllers/admin/offers_controller.rb
class Admin::OffersController < Admin::AdminController
  before_action :authenticate_venue_admin!
  before_action :set_venue, only: %i[new create edit update]
  before_action :set_offer, only: %i[show edit destroy update select_variant remove_variant]

  def index
    if params[:venue_id]
      @venue = Venue.find(params[:venue_id])
      @offers = @venue ? @venue.offers : []
    else
      @offers = Offer.all
      @venue = nil
    end
  end

  def show
    @variants ||= @offer.variants.order(price: :desc)
    @venue = @offer.venue
  end

  def new
    if @venue.nil?
      redirect_to admin_offers_path, alert: 'Venue not found.'
    else
      @offer = @venue.offers.build
    end
  end

  def create
    if @venue.nil?
      redirect_to admin_offers_path, alert: 'Venue not found.'
    else
      @offer = @venue.offers.build(offer_params)
      if @offer.save
        respond_to do |format|
          format.html { redirect_to admin_venue_path(@venue), notice: 'Offer was successfully created.' }
          format.turbo_stream
        end
      else
        render :new
      end
    end
  end

  def edit; end

  def update
    if @offer.update(offer_params)
      redirect_to admin_offer_path(@offer), notice: 'Offer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @offer.destroy
      respond_to do |format|
        format.html { redirect_to admin_venue_path(@offer.venue), notice: 'Offer was successfully deleted.' }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to admin_venue_path(@offer.venue), alert: 'Failed to delete offer.' }
        format.turbo_stream
      end
    end
  end

  def select_variant
    @variant = @offer.variants.find(params[:variant_id])

    session[:selected_variants] ||= []
    session[:selected_variants] |= [@variant.id]
  end

  def remove_variant
    session[:selected_variants].delete(params[:variant_id].to_i)
    redirect_to selected_variants_admin_offers_path, notice: 'Variant removed successfully'
  end

  def selected_variants
    @selected_variants = Variant.where(id: session[:selected_variants] || [])
    @total_price = @selected_variants.sum(&:price)
    @venue_id = @selected_variants.first&.offer&.venue_id

    return unless @venue_id.nil?

    redirect_to admin_offers_path, alert: 'No variants selected or unable to determine venue.'
  end

  private

  def set_venue
    @venue = Venue.find_by(id: params[:venue_id]) if params[:venue_id]
  end

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:title, :description, :venue_id,
                                  variant_attributes: %i[id price_type price _destroy])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_venue_admin!
  before_action :set_venue, only: [:new, :create, :edit, :update]
  before_action :set_offer, only: [:show, :edit, :destroy, :update, :select_variant, :remove_variant]
  
  def index
    if params[:venue_id]
      @venue = Venue.find_by(id: params[:venue_id])
      @offers = @venue ? @venue.offers : []
    else
      @offers = Offer.all
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @variants ||= @offer.variants.order(price: :desc) if @offer
    @venue = @offer.venue
  end

  def new
    @offer = @venue.offers.build
  end
  
  def create
    @offer = @venue.offers.build(offer_params)
    if @offer.save
      respond_to do |format|
        format.html { redirect_to venue_path(@venue), notice: 'Offer was successfully created.' }
        format.turbo_stream
      end
    else
      render :new
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: 'Offer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @offer.destroy
      respond_to do |format|
        format.html { redirect_to venue_path(@offer.venue), notice: 'Offer was successfully deleted.' }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to venue_path(@offer.venue), alert: 'Failed to delete offer.' }
        format.turbo_stream
      end
    end
  end

  def select_variant
    @variant = @offer.variants.find(params[:variant_id])
    
    session[:selected_variants] ||= []
    session[:selected_variants] << @variant.id
    
    redirect_to selected_variants_offers_path, notice: 'Variant selected successfully'
  end

  def remove_variant
    session[:selected_variants].delete(params[:variant_id].to_i)
    redirect_to selected_variants_offers_path, notice: 'Variant removed successfully'
  end

  def selected_variants
    @selected_variants = Variant.where(id: session[:selected_variants] || [])
    @total_price = @selected_variants.sum(&:price)
    @venue_id = @selected_variants.first&.offer&.venue_id
  end

  private

  def set_venue
    @venue = Venue.find_by(id: params[:venue_id])
  end
  
  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:title, :description, :venue_id, variant_attributes: [:id, :price_type, :price, :_destroy])
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_offer.html.erb
<div id="<%= dom_id(offer) %>">
  <h3><%= link_to offer.title, venue_offer_path(offer.venue, offer) %></h3>
  <p><%= offer.description %></p>

  <% selected_variant_ids = session[:selected_variants] || [] %>
  <% total_price = offer.total_price(selected_variant_ids) %>
  <p>Total Price: <%= number_to_currency(total_price) %></p>

  <% offer.variants.each do |variant| %>
    <div class="variant mb-3">
      <p>Variant: <%= variant.name %></p>
      <p>Price: <%= number_to_currency(variant.price) %></p>
      <p>Period: <%= variant.period %></p>
      <%= button_to 'Select Variant', select_variant_offer_path(offer, variant_id: variant.id), method: :post, class: 'btn btn-outline-primary' %>
    </div>
  <% end %>

  <%= link_to 'Delete Offer', offer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
</div>

app/views/offers/edit.html.erb
<h1>Edit Offer</h1>

<%= form_with(model: @offer, local: true) do |form| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>
      <ul>
        <% @offer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :venue_id %>
    <%= form.collection_select :venue_id, Venue.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Offer' %>
  </div>
<% end %>

<%= link_to 'Back', offer_path(@offer) %>

app/views/offers/index.html.erb
<h1>All Offers</h1>

<%= link_to 'New Offer', new_venue_offer_path(@venue), class: 'btn btn-primary' %>

<% @offers.each do |offer| %>
  <div class="offer">
    <h2><%= link_to offer.title, offer_path(offer) %></h2>
    
    <% if offer.venue %>
      <p>Venue: <%= link_to offer.venue.name, venue_path(offer.venue) %></p>
      <p>Address: <%= offer.venue.address.street %>, <%= offer.venue.address.city %>, <%= offer.venue.address.country %></p>
    <% end %>
    
    <% offer.variants.each do |variant| %>
      <div class="variant">
        <p>Variant:</p>
        <p><%= variant.name %></p>
        <p>Price: <%= number_to_currency(variant.price) %></p>
        <p>Period: <%= variant.period %></p>
        <%= button_to 'Select Variant', select_variant_offer_path(offer, variant_id: variant.id), method: :post, class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/offers/selected_variants.html.erb
<h1>Selected Variants</h1>

<% if @selected_variants.any? %>
  <ul>
    <% @selected_variants.each do |variant| %>
      <li>
        Venue: <%= variant.offer.venue.name %> <br>
        Offer: <%= variant.offer.title %> <br>
        Variant: <%= variant.name %> <br>
        Price: <%= number_to_currency(variant.price) %> <br>
        Period: <%= variant.period %> <br>
        <%= link_to 'Remove Variant', remove_variant_offer_path(variant.offer, variant_id: variant.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
      </li>
    <% end %>
  </ul>
  <p>Total Price: <%= number_to_currency(@total_price) %></p>
  <%= link_to 'Proceed to Reservation', new_venue_reservation_path(@venue_id), class: 'btn btn-primary' %>
<% else %>
  <p>No variants selected yet.</p>
  <%= link_to 'Back to Offers', offers_path, class: 'btn btn-secondary' %>
<% end %>